function [movies, movieParams] = create_drift_grating_patterns(orientations, spatialFreqs, temporalFreqs, phases, contrast, bg, dispWidth, dispHeight, ppcm, n_trial, movieDuration, frameRate)
% create_drift_grating_patterns_vectorized generates drifting grating movies using vectorization.
%
% Inputs and outputs are the same as in your original function.
%
% The drifting movie is generated by updating the phase over time:
%    phase(t) = initialPhase + 2*pi*temporalFreq*t

    % Set luminance levels and amplitude
    gray = bg;
    amplitude = contrast * gray;
    
    % Calculate number of frames in each movie
    nFrames = round(movieDuration * frameRate);
    
    % Total unique stimuli from combinations of parameters.
    nOrient = length(orientations);
    nFreq   = length(spatialFreqs);
    nTemp   = length(temporalFreqs);
    nPhase  = length(phases);
    nStim   = nOrient * nFreq * nTemp * nPhase;
    
    % Preallocate base movie array (4D: height x width x frames x nStim)
    baseMovies = zeros(dispHeight, dispWidth, nFrames, nStim, 'uint8');
    
    % Preallocate base parameter list
    baseParams = struct('orientation', [], 'spatialFreq', [], 'temporalFreq', [], 'phase', []);
    
    % Create coordinate grid (centered)
    [x, y] = meshgrid(1:dispWidth, 1:dispHeight);
    x = x - dispWidth / 2;
    y = y - dispHeight / 2;
    
    % Pixel size in cm
    pixel_size_cm = 1 / ppcm;
    
    % Viewing distance in cm (adjust as needed)
    viewingDist = 20;
    
    % Calculate degrees per pixel
    deg_per_pixel = 2 * atan(pixel_size_cm / (2 * viewingDist)) * (180 / pi);
    
    % Precompute time vector as a 1x1xnFrames array for vectorized computation.
    t = reshape((0:nFrames-1) / frameRate, [1, 1, nFrames]);
    
    % Stimulus counter
    stimIdx = 1;
    
    % Loop through each combination of orientation, spatial frequency,
    % temporal frequency and phase.
    for o = 1:nOrient
        theta = orientations(o) * pi / 180; % Convert to radians
        for f = 1:nFreq
            freq_cpd = spatialFreqs(f); % cycles per degree
            % Convert spatial frequency to cycles per pixel
            freq_cpp = freq_cpd * deg_per_pixel;
            
            % Rotate the coordinate grid according to orientation.
            xt = x * cos(theta) + y * sin(theta);
            
            for tIdx = 1:nTemp
                tempFreq = temporalFreqs(tIdx); % temporal frequency in Hz
                
                for p = 1:nPhase
                    phaseVal = phases(p); % initial phase as a fraction of a cycle
                    initialPhase = phaseVal * 2 * pi; % in radians
                    
                    % Compute phase offsets for all frames at once.
                    phaseOffsets = initialPhase + 2 * pi * tempFreq * t;
                    % Compute the full movie by vectorizing the cosine calculation.
                    % xt is (dispHeight x dispWidth) and phaseOffsets is (1 x 1 x nFrames),
                    % which MATLAB will automatically expand.
                    grating3D = gray + amplitude * cos(2*pi*freq_cpp * xt + phaseOffsets);
                    
                    % Clip the values and convert to uint8.
                    grating3D = uint8(min(max(grating3D, 0), 255));
                    
                    % Store the generated movie and its parameters.
                    baseMovies(:, :, :, stimIdx) = grating3D;
                    baseParams(stimIdx).orientation = orientations(o);
                    baseParams(stimIdx).spatialFreq = freq_cpd;
                    baseParams(stimIdx).temporalFreq = tempFreq;
                    baseParams(stimIdx).phase = phaseVal;
                    
                    stimIdx = stimIdx + 1;
                end
            end
        end
    end
    
    % Replicate the base stimuli n_trial times in a randomized order.
    totalStim = nStim * n_trial;
    movies = zeros(dispHeight, dispWidth, nFrames, totalStim, 'uint8');
    
    % Preallocate parameter output.
    movieParams = struct('orientation', cell(totalStim, 1), ...
                         'spatialFreq', cell(totalStim, 1), ...
                         'temporalFreq', cell(totalStim, 1), ...
                         'phase', cell(totalStim, 1));
    
    % Create a repeated index vector for the base stimuli.
    baseIndices = repmat(1:nStim, 1, n_trial);
    
    % Randomize the sequence.
    randOrder = baseIndices(randperm(totalStim));
    
    % Assemble the final movies array and corresponding parameters.
    for i = 1:totalStim
        idx = randOrder(i);
        movies(:, :, :, i) = baseMovies(:, :, :, idx);
        movieParams(i).orientation = baseParams(idx).orientation;
        movieParams(i).spatialFreq = baseParams(idx).spatialFreq;
        movieParams(i).temporalFreq = baseParams(idx).temporalFreq;
        movieParams(i).phase = baseParams(idx).phase;
    end
    
    disp(['Generated ', num2str(totalStim), ' drifting grating movies (', num2str(nStim), ' unique stimuli repeated ', num2str(n_trial), ' times in random order).']);
end
